name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
        
      - name: Build Go app
        run: go build -o app

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: docker.io/myuser/myapp:latest
          
      - name: Run vulnerability scan
        uses: docker://alpine:3.15
        with:
          entrypoint: sh
          args: ["-c", "apk update && apk add git && go get github.com/carbonetes/jacked && jacked -path /github/workspace"]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
