# name: optional, title of the github action
name: Jacked Scan
# on: github action like pull-request, push, events
on: [push, pull_request]
# jobs: one or more
jobs:
  jacked: #jacked: is the custom name of the build:
    runs-on: ubuntu-latest

    steps: # steps: can run commands, setup tasks OR run an action
      - uses: actions/checkout@v3 # uses: select an action, actions based on "github.com/actions" then this will call the github.com/actions -> action.yml, the @latest: is the version release
        name: Checking out...
        
      - uses: actions/setup-go@v3
        name: Installing go...
        with:
          go-version: 1.19
      - run: go version
      - run: go mod tidy
      - run: go run .
    
      
