name: Jacked vulnerability scan
on:
  push:
    branches:
      main
jobs:
  jacked:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Jacked vulnerability scan
        uses: docker://carbonetes/jacked:latest
        with:
          args: jacked --ci
