name: Jacked Vulnerability Scan

on:
  push:
    branches: [ main ]

jobs:
  jacked:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Jacked vulnerability scan
      id: jacked_scan
      uses: docker://alpine/alpine:latest
      with:
        args: --dir ./~/ --output-format json

    - name: Upload Jacked report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Jacked Report
        path: |
          ./~/jacked-report.json
