name: Jacked Scan
on: [push, pull_request]

jobs:
  jacked:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Jacked
        run: |
          npm install -g @carbonetes/jacked
      - name: Run Jacked Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jacked scan
