name: Diggity Action
on: [push, pull_request]
jobs:
  diggity:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest] # can add more os: windows-latest, macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: BOM Diggity Action
      # You may pin to the exact commit or the version.
      # uses: carbonetes/diggity-action@7cb15cd68857ac6c737f6915b6714a970b57284e
        uses: carbonetes/diggity-action@v1.0.0
        with:
          # The path to the directory to be scanned (default scanning option).
          directory: .
          # The desired SBOM output type (default table).
          output_type: table
          # Specify enabled parsers (default all).
          enabled_parsers: all
          # Save SBOM results to the output file.
          output_file: sbom.jsom
          # Disables file listing from package metadata (default false).
          disable_file_listing: false
          # Disables secret search (default false).
          disable_secret_search: false
          # Exclude secret searching for each specified filenames.
          secret_exclude_filenames: false
          # Maximum file size that the secret will search (default 10485760).
          secret_max_file_size: false
          # Secret content regex are searched within files that matches the provided regular expression.
          secrets_content_regex: false
